<a href="https://colab.research.google.com/github/marybello/decision-trees-algorithm/blob/master/decision_trees.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

#import the dataset

dataset = pd.read_csv('iris.csv')
#select the dependent and independent variable

X = dataset.iloc[:,1:5]
y= dataset.iloc[:,5]

In [2]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.3,random_state=0)

In [3]:
# Fitting Decision Tree to Training set
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(criterion='entropy', random_state=0)
classifier.fit(X_train, y_train)
# Predicting Test set results
y_pred = classifier.predict(X_test)


In [5]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

from sklearn import metrics
#accuracy score
accuracy = metrics.accuracy_score(y_test, y_pred) *100
print(accuracy)

[[16  0  0]
 [ 0 17  1]
 [ 0  0 11]]
97.77777777777777


In [8]:
#using random forest
from sklearn.ensemble import RandomForestClassifier
classifier2= RandomForestClassifier(n_estimators=5, criterion='entropy',random_state=0)
classifier2.fit(X_train,y_train)

#predicting test result
y_pred2 = classifier2.predict(X_test)

from sklearn import metrics
#accuracy score
accuracy2 = metrics.accuracy_score(y_test, y_pred2) *100
print(accuracy2)

97.77777777777777
